#include <stdio.h>
#include <stdlib.h>
#include <math.h>

int main(int argc, char **argv) {
	int i;
	int l;

	/* values we eventually want for EEPROM */
	double lvd[4];
	int lvd_ee[4];
	double lvr[4];
	int lvr_ee[4];
	int delay[4];
	int delay_ee[4];

	/* APO6150 ADC and voltage divider */
	double rtop, rbottom;
	double vdiv_ratio;

	double adc_bits;
	double adc_max_value;
	double vref;
	double v_per_bit;

	printf("# configuration information - hard coded for APO6150:\n");

	rtop=49900.0;
	rbottom=10000.0;
	vdiv_ratio = rbottom / ( rtop + rbottom );
	printf("\trtop=%0.1f rbottom=%0.1f vdiv_ratio=%0.4f\n",rtop,rbottom,vdiv_ratio);

	adc_bits=10.0;
	adc_max_value=pow(2.0,adc_bits)-1.0;
	vref=5.0;
	v_per_bit=vref/adc_max_value;
	printf("\tadc_bits=%0.1f adc_max_value=%0.1f vref=%0.1f v_per_bit=%0.6f\n",
			adc_bits,
			adc_max_value,
			vref,
			v_per_bit);

	printf("\n");


	if ( argc != 13 ) {
		printf("# usage: %s lvd[0] ... lvd[3] lvr[0] .... lvr[3] delay[0] ... delay[3]\n",argv[0]);
		return 1;
	}

	printf("# LVD table:\n");
	for ( i=0 ; i<4 ; i++ ) {
		double vdiv_out;

		lvd[i]=atof(argv[i+1]);
		vdiv_out = lvd[i]*vdiv_ratio;
		lvd_ee[i]=(int) (vdiv_out / v_per_bit);

		printf("\tlvd[%d]=%0.2f vdiv_out=%0.4f adc=%d\n",i,lvd[i],vdiv_out,lvd_ee[i]);
	}

	printf("# LVR table:\n");
	for ( i=0 ; i<4 ; i++ ) {
		double vdiv_out;

		lvr[i]=atof(argv[i+5]);
		vdiv_out = lvr[i]*vdiv_ratio;
		lvr_ee[i]=(int) (vdiv_out / v_per_bit);

		printf("\tlvr[%d]=%0.2f vdiv_out=%0.4f adc=%d\n",i,lvr[i],vdiv_out,lvr_ee[i]);
	}

	printf("# Off delay table:\n");
	for ( i=0 ; i<4 ; i++ ) {
		double vdiv_out;

		delay_ee[i]=delay[i]=(int) atof(argv[i+9]);

		printf("\tdelay[%d]=%d (seconds) %0.5f (minutes)\n",i,delay[i],(double) (delay[i] / 60.0));
	}


printf("\n");
printf("/*\nEEPROM table for LVD, LVR, off delay, and serial number\n");
printf("generated by the following command:\n");
for ( i=0 ; i<argc ; i++ ) {
	printf("%s ",argv[i]);
}
printf("\n*/\n");

printf("#rom 0x2100 = {\n");

/* LVD */
printf("\t");
for ( i=0 ; i<4 ; i++ ) {
	printf("0x%02x, 0x%02x, ",(unsigned char) (lvd_ee[i]>>8), (unsigned char) (lvd_ee[i]&0xff));
}
printf("/* LVD = { ");
for ( i=0; i<4 ; i++ ) {
	printf("%0.2f ",lvd[i]);
}
printf("} volts */\n");

/* LVR */
printf("\t");
for ( i=0 ; i<4 ; i++ ) {
	printf("0x%02x, 0x%02x, ",(unsigned char) (lvr_ee[i]>>8), (unsigned char) (lvr_ee[i]&0xff));
}
printf("/* LVR = { ");
for ( i=0; i<4 ; i++ ) {
	printf("%0.2f ",lvr[i]);
}
printf("} volts */\n");

/* delay */
printf("\t");
for ( i=0 ; i<4 ; i++ ) {
	printf("0x%02x, 0x%02x, ",(unsigned char) (delay_ee[i]>>8), (unsigned char) (delay_ee[i]&0xff));
}
printf("/* OFF DELAY = { ");
for ( i=0; i<4 ; i++ ) {
	printf("%d ",delay[i]);
}
printf("} seconds */\n");

printf("\t0x00, 0x00, 0x00, 0x02 } /* SERIAL NUMBER is always 2 for APO6150 - signifies auto 12/24 volt */\n");





	return 0;

}
